### ISSUE TITLE
seting multiple alternatives to the same path

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-alternatives#41]
### Affected Puppet, Ruby, OS and module versions/distributions
- Module version: 1.0.1
### How to reproduce (e.g Puppet code you use)

In trying to follow [Neovim's instalation](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu) instructions to point `vi`, `vim`, and `editor` to the same binary (`/usr/bin/nvim`):

``` puppet
# install nvim as alternatives for various things…
Alternative_entry {
  ensure   => present,
  priority => 60,
  require  => Package[neovim],
}

# currently puppet/alternatives can only configure one laternative per path
alternative_entry { 'nvim as vim':
  name     => '/usr/bin/nvim',
  altlink  => '/usr/bin/vim',
  altname  => 'vim',
}
alternative_entry { 'nvim as vi':
  name     => '/usr/bin/nvim',
  altlink  => '/usr/bin/vi',
  altname  => 'vi',
}
alternative_entry { 'nvim as editor':
  name     => '/usr/bin/nvim',
  altlink  => '/usr/bin/editor',
  altname  => 'editor',
}

Alternatives {
  require => Package[neovim],
}
alternatives { 'vim':
  path => '/usr/bin/nvim',
}
alternatives { 'vi':
  path => '/usr/bin/nvim',
}
alternatives { 'editor':
  path => '/usr/bin/nvim',
}
```
### What are you seeing

```
Error: Evaluation Error: Error while evaluating a Resource Statement, Cannot alias Alternative_entry[nvim as vi] to ["/usr/bin/nvim"] at /etc/puppetlabs/code/environments/production/manifests/sinix.pp:78; resource ["Alternative_entry", "/usr/bin/nvim"] already declared at /etc/puppetlabs/code/environments/production/manifests/sinix.pp:73 at /etc/puppetlabs/code/environments/production/manifests/sinix.pp:78:1 on node sinix.home
```
### What behaviour did you expect instead

I'd expect it to work… there are a lot of programs which have different behaviour, depending on how they are called.

**Comment by ffrank** [comment]
Looks like a rather severe design error.

Yes, the alternative's `name` cannot map to `name` and be namevar, because by its nature, you need more than one alternative that share the same `name`. However, it's plain that there can also be several independent alternatives with different names (alternatives for different things) that point to the same binary. So the `path` (in alternative terms) is not unique at all.

What *is* probably unique is the `name+path` combination, forming a distinct alternative for `name`. Going for a composite namevar, however, would likely be absolute overkill.

Proposal: Make the `name` parameter meaningless. Add a `path` property that takes the role of the current `name` parameter. The wrinkle being that it will allow managing the same resource twice or more, like:

```
alternative_entry { 'nvim as vim':
  path     => '/usr/bin/nvim',
  altlink  => '/usr/bin/vim',
  altname  => 'vim',
}
alternative_entry { 'trololol':
  path     => '/usr/bin/nvim',
  altlink  => '/usr/bin/vim',
  altname  => 'vim',
  priority => 9000,
}
```

Still, I rather feel that this inconvenience is not worth the hassle of dealing with composite namevars. Unless, of course, @crayfishx wishes to step up and do the fun part ;-)

(Note, I especially love how the provider has a [name= method](https://github.com/voxpupuli/puppet-alternatives/blob/4062ffb907d01f48ed28ffde12b18a819987e890/lib/puppet/provider/alternative_entry/dpkg.rb#L71-L75) despite `name` not being a property.)

**Comment by crayfishx** [comment]
@ffrank I don't think composite namevars are overkill at all, in fact, I think it's very appropriate for this type.   I'll try and contribute the 'fun part' ;-)...

**Comment by crayfishx** [comment]
I would much rather see composite namevars than the leave it open to duplicate resource declarations like in your example.

**Comment by ffrank** [comment]
Cool. And yes, that will probably be the only way to build a really clean abstraction.

**Comment by igalic** [comment]
can't we just fix this by using title and name distinctly?
or… use better… names?

**Comment by ffrank** [comment]
Well, you can always make `name` to be meaningless, so that resource titles become arbitrary.

However (and this is a big one), this allows users to manage any entity with multiple resources (that have different, meaningless names/titles). So that would be quite horrible as well. Let's not do that.
